### PR TITLE
Force the cleanup script to use the tool cache

### LINKED ISSUE #120: JFrog CLI not reading environment variables correctly
### Describe the bug

A previously working reference to `setup-jfrog-cli@v3` stopped working. The root cause is that the `JF_URL` environment variable does not appear to be recognized. The changed code is here: https://github.com/jfrog/setup-jfrog-cli/pull/117/files#diff-39b2554fd18da165b59a6351b1aafff3714e2a80c1435f2de9706355b4d32351R86

It looks like there are unit tests for this specific use case, I cannot tell from looking at the code exactly what is going wrong. 

### Current behavior

The following error:
```
Error: 'download-repository' input provided, but no JFrog environment details found. Hint - Ensure that the JFrog connection details environment variables are   Error: 'download-repository' input provided, but no JFrog environment details found. Hint - Ensure that the JFrog connection details environment variables are set: either a Config Token with a JF_ENV_ prefix or separate env config (JF_URL, JF_USER, JF_PASSWORD, JF_ACCESS_TOKEN)set: either a Config Token with a JF_ENV_ prefix or separate env config (JF_URL, JF_USER, JF_PASSWORD, JF_ACCESS_TOKEN)
```

### Reproduction steps

We are using the action in the following GitHub Action job step:

```
- name: Setup JFrog CLI
        if: steps.validate.outcome == 'success'
        uses: jfrog/setup-jfrog-cli@v3
        env:
          JF_URL: https://artifactory.tools.bestbuy.com/
          JF_USER: ${{ env.ARTIFACTORY_USERNAME }}
          JF_ACCESS_TOKEN: ${{ env.ARTIFACTORY_ACCESS_TOKEN }}
        with:
          download-repository: generic-jfrog-cli-remote
          version: latest
``

### Expected behavior

Action to complete successfully.This action stopped working with the push of 3.5.0 a few hours ago and we solved issue by pinning version to 3.4.2. 

### Setup JFrog CLI version

3.5.0

### JFrog CLI version

default (2.52.7)

### Workflow operating system type and version

Ubuntu 22.04

### JFrog Artifactory version (if relevant)

Artifactory EnterpriseX 7.71.11

### JFrog Xray version (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by yahavi**
- [x] All [tests](https://github.com/jfrog/setup-jfrog-cli#build-the-code) passed. If this feature is not already covered by the tests, I added new tests.
- [x] I used `npm run format` for formatting the code before submitting the pull request.
-----

Fix #120 

In the cleanup stage, use JFrog CLI from the cache and avoid downloading it. Before this pull request, we downloaded the JFrog CLI when the version was set to "latest".

### CODE REVIEW

File: src/utils.ts [hunk 1]
```diff
@@ -179,6 +179,23 @@ export class Utils {
         await this.cacheAndAddPath(downloadDir, version, jfrogFileName);
     }
 
+    /**
+     * Fetch the JFrog CLI path from the tool cache and append it to the PATH environment variable. Employ this approach during the cleanup phase.
+     */
+    public static async addCachedCliToPath(): Promise<boolean> {
```
Comment (sverdlov93) [inline src/utils.ts:185]: dont need the async/promise
