### PR TITLE
Fix authentication flows

### LINKED ISSUE #121: Exchanging JSON web token with an access token failed: Input required and not supplied: oidc-provider-name
### Describe the bug

env variables are not recognized - regression in v3.5.0

githubenv variables are not recognized, causing fallback to OICD which fails with this error

### Current behavior

2024-01-17T17:02:34.2039427Z ::group::Setup JFrog CLI
2024-01-17T17:02:34.2039979Z ##[group]Setup JFrog CLI
2024-01-17T17:02:34.2056995Z ##[debug]Searching for JF_URL
2024-01-17T17:02:34.2057524Z ##[debug]JF_URL found
2024-01-17T17:02:34.2058097Z ##[debug]Searching for JF_ACCESS_TOKEN, JF_USER and JF_PASSWORD
2024-01-17T17:02:34.2059057Z JF_ACCESS_TOKEN and JF_USER + JF_PASSWORD weren't found. Getting access token using OpenID Connect
2024-01-17T17:02:34.2059835Z ##[debug]Fetching JSON web token
2024-01-17T17:02:34.2061755Z ##[debug]ID token url is https://pipelinesghubeus26.actions.githubusercontent.com/k75H1DBAfn7O6Mo0TRQmb014cDWVwCbkrZ6RY4JoockeD1mW9W/00000000-0000-0000-0000-000000000000/_apis/distributedtask/hubs/Actions/plans/a5b3151a-44ff-4c0a-bb81-7544446f9994/jobs/6604c111-019b-5ed5-ae03-3fa9f8925512/idtoken?api-version=2.0
2024-01-17T17:02:34.3042451Z ::add-mask::***
2024-01-17T17:02:34.3045055Z ##[debug]Exchanging JSON web token with an access token
2024-01-17T17:02:34.3070577Z ##[error]Exchanging JSON web token with an access token failed: Input required and not supplied: oidc-provider-name
2024-01-17T17:02:34.3071739Z ::endgroup::
2024-01-17T17:02:34.3072010Z ##[endgroup]
2024-01-17T17:02:34.3123024Z ##[debug]Node Action run completed with exit code 1
2024-01-17T17:02:34.3125937Z ##[debug]JFROG_CLI_ENV_EXCLUDE='password;secret;key;token;auth;JF_ARTIFACTORY_;JF_ENV_;JF_URL;JF_USER;JF_PASSWORD;JF_ACCESS_TOKEN'
2024-01-17T17:02:34.3126916Z ##[debug]JFROG_CLI_OFFER_CONFIG='false'
2024-01-17T17:02:34.3127418Z ##[debug]JFROG_CLI_BUILD_NAME='goldenfrog-demo'
2024-01-17T17:02:34.3127921Z ##[debug]JFROG_CLI_BUILD_NUMBER='50'
2024-01-17T17:02:34.3128783Z ##[debug]JFROG_CLI_BUILD_URL='***********'
2024-01-17T17:02:34.3130110Z ##[debug]JFROG_CLI_USER_AGENT='setup-jfrog-cli-github-action/3.5.0'

### Reproduction steps

setup jfrog cli using setup action v3.5.0

### Expected behavior

no error

### Setup JFrog CLI version

3.5.0

### JFrog CLI version

2.52.9

### Workflow operating system type and version

linux, ubuntu 

### JFrog Artifactory version (if relevant)

_No response_

### JFrog Xray version (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by yahavi**
- [x] All [tests](https://github.com/jfrog/setup-jfrog-cli#build-the-code) passed. If this feature is not already covered by the tests, I added new tests.
- [x] I used `npm run format` for formatting the code before submitting the pull request.
-----

Fix #121 

* Fix anonymous access
* Fix authentication with username + access token
* When there are no credentials provided, allow at least downloading the CLI
* Fix integration test to run search command instead of ping, because ping is allowed without credentials
* Make the integration test run on forks, if credentials provided

### CODE REVIEW

File: lib/utils.js [hunk 1]
```diff
@@ -51,14 +51,11 @@ class Utils {
     static getJfrogCredentials() {
         return __awaiter(this, void 0, void 0, function* () {
             let jfrogCredentials = this.collectJfrogCredentialsFromEnvVars();
-            if (!jfrogCredentials.jfrogUrl) {
-                return jfrogCredentials;
-            }
-            // If the required credentials, such as the access token or a combination of username and password, are available, the process terminates without triggering the OIDC flow
-            if (jfrogCredentials.accessToken || (jfrogCredentials.username && jfrogCredentials.password)) {
+            if (!jfrogCredentials.jfrogUrl || jfrogCredentials.password || jfrogCredentials.accessToken || !process.env.ACTIONS_ID_TOKEN_REQUEST_URL) {
```
Comment (sverdlov93) [inline lib/utils.js:54]: confusing if

File: lib/utils.js [hunk 2]
```diff
@@ -79,23 +76,20 @@ class Utils {
...
-            core.debug('JF_URL found');
-            jfrogCredentials.jfrogUrl = process.env.JF_URL;
+        let jfrogCredentials = {
+            jfrogUrl: process.env.JF_URL,
+            accessToken: process.env.JF_ACCESS_TOKEN,
+            username: process.env.JF_USER,
+            password: process.env.JF_PASSWORD,
+        };
+        if (jfrogCredentials.password && !jfrogCredentials.username) {
+            throw new Error('JF_PASSWORD is configured, but the JF_USER environment variable was not set.');
```
Comment (sverdlov93) [inline lib/utils.js:89]: why error? what about ConfigToken case?

**Review by eyalbe4 — CHANGES_REQUESTED** [review]

File: src/utils.ts [hunk 3]
```diff
@@ -76,28 +72,45 @@ export class Utils {
...
+        if (!jfrogCredentials.jfrogUrl) {
+            // If no JFrog URL is specified, we can't use OpenID Connect
+            return false;
+        }
+        if (jfrogCredentials.password || jfrogCredentials.accessToken) {
+            // If credentials are specified - use them instead
+            return false;
+        }
+        if (!process.env.ACTIONS_ID_TOKEN_REQUEST_URL) {
+            // Only if the user added the 'id-token: write' permission, this environment variable was set
```
Comment (sverdlov93) [inline src/utils.ts:90]:
```suggestion
            // To use OpenIDConnect auth the user should set the ‘id-token: write’ permission that sets the process.env.ACTIONS_ID_TOKEN_REQUEST_URL. If it's empty then shouldn't use Oidc.
```

also make this the first 'if'
